package lecho.lib.hellocharts.model;

import android.graphics.Color;

/**
 * Base class for most chart data models.
 */
public abstract class AbstractChartData implements ChartData {
	public static final int DEFAULT_TEXT_SIZE_SP = 12;
	protected Axis axisX = new Axis();
	protected Axis axisY = new Axis();
	protected int axesColor = Color.LTGRAY;
	protected int axesLabelTextSize = DEFAULT_TEXT_SIZE_SP;
	protected int valueLabelTextColor = Color.WHITE;
	protected int valueLabelTextSize = DEFAULT_TEXT_SIZE_SP;
	protected int maxLabelChars = 5;

	public AbstractChartData() {

	}

	public AbstractChartData(AbstractChartData data) {
		this.axisX = new Axis(data.axisX);
		this.axisY = new Axis(data.axisY);
		this.axesColor = data.axesColor;
		this.axesLabelTextSize = data.axesLabelTextSize;
		this.valueLabelTextColor = data.valueLabelTextColor;
		this.valueLabelTextSize = data.valueLabelTextSize;
		this.maxLabelChars = data.maxLabelChars;
	}

	public void setAxisX(Axis axisX) {
		if (null == axisX) {
			this.axisX = new Axis().setAutoGenerated(false);
		} else {
			this.axisX = axisX;
		}
	}

	public Axis getAxisX() {
		return axisX;
	}

	public void setAxisY(Axis axisY) {
		if (null == axisY) {
			this.axisY = new Axis().setAutoGenerated(false);
		} else {
			this.axisY = axisY;
		}
	}

	public Axis getAxisY() {
		return axisY;
	}

	public int getAxesColor() {
		return axesColor;
	}

	public void setAxesColor(int axesColor) {
		this.axesColor = axesColor;
	}

	public int getAxesLabelTextSize() {
		return axesLabelTextSize;
	}

	public void setAxesLabelTextSize(int axesLabelTextSize) {
		this.axesLabelTextSize = axesLabelTextSize;
	}

	public int getValueLabelTextColor() {
		return valueLabelTextColor;
	}

	public void setValueLabelsTextColor(int valueLabelTextColor) {
		this.valueLabelTextColor = valueLabelTextColor;
	}

	public int getValueLabelTextSize() {
		return valueLabelTextSize;
	}

	public void setValueLabelTextSize(int valueLabelTextSize) {
		this.valueLabelTextSize = valueLabelTextSize;
	}

	@Override
	public void setMaxLabelChars(int numChars) {
		if (numChars < 0) {
			numChars = 0;
		} else if (numChars > 32) {
			numChars = 32;
		}
		maxLabelChars = numChars;
	}

	@Override
	public int getMaxAxisLabelChars() {
		return maxLabelChars;
	}

}